#!/bin/bash
# now issue single string comment

parse_args() {
  optspec=":hp-:"
  while getopts "$optspec" optchar; do
      case "${optchar}" in
          -)
              case "${OPTARG}" in
                  key-bits)
                      val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                      #echo "Parsing option: '--${OPTARG}', value: '${val}'" >&2
                      putit_sshkey_bits=${val}
                      ;;
                  key-name)
                      val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                      #echo "Parsing option: '--${OPTARG}', value: '${val}'" >&2
                      putit_sshkey_name=${val}
                      ;;
                  key-type)
                      val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                      #echo "Parsing option: '--${OPTARG}', value: '${val}'" >&2
                      putit_sshkey_type=${val}
                      ;;
                  key-comment)
                      val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
                      #echo "Parsing option: '--${OPTARG}', value: '${val}'" >&2
                      putit_sshkey_comment=${val}
                      ;;
                  password)
                      putit_sshkey_passphrase='true'
                      ;;
                  help)
                      get_help
                      exit 1
                      ;;
                  *) 
                      echo "${optspec:0:1} ${OPTARG}" 
                      #if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
                      if [ "$OPTERR" = 1 ]; then
                          echo -e "Unknown option --${OPTARG}\n" >&2
                          get_help  
                          exit 1
                      fi
                      ;;
              esac;;
          h) 
              get_help
              exit 1
              ;;
          *)
              if [ "$OPTERR" = 1 ] || [ "${optspec:0:1}" = ":" ]; then
                  echo "Non-option argument: '-${OPTARG}'" >&2
                  exit 1
              fi
              ;;
      esac
  done
  # obligatory paramas goes here and default values if they have one
  if [ -z ${putit_sshkey_name} ]; then 
    get_help
    exit 1
  fi

  # defaults ones
  if [ -z ${putit_sshkey_bits+x} ]; then 
    putit_sshkey_bits=2048
  fi
  if [ -z ${putit_sshkey_type+x} ]  ; then
    putit_sshkey_type='RSA'
  fi
  if [ -z ${putit_sshkey_comment+x} ]; then 
    local date=`date '+%Y-%m-%d %H:%M:%S %Z'`
    putit_sshkey_comment="Generated by putit CLI at ${date}"
  fi
}
